// src/pwa/serviceWorkerTemplate.ts
//
// Pure renderer for the hand-rolled service worker. The PWA build plugin (vite.config.ts)
// collects the fingerprinted asset filenames Rollup emits for a build, plus the static shell
// members from public/ (manifest, icons), and stamps them into this template as the precache
// manifest. Keeping the renderer here (rather than inline in vite.config) makes it a pure,
// unit-testable function — the SW's invariants (three lifecycle listeners, exact precache set,
// version-keyed cache) are then verifiable in Vitest without a browser.
//
// Strategy (see CLAUDE.md Principle I — depth: this replicates the one thing Workbox does that a
// static hand-rolled SW cannot, namely cache-bust hashed Vite assets, with zero new dependencies):
//   • install  → precache the whole app shell (index.html + fingerprinted JS/CSS + manifest + icons)
//   • activate → delete every cache whose key ≠ the current build version (purge stale shells)
//   • fetch    → navigations: network-first, fall back to the cached shell when offline;
//                static assets: cache-first (Vite fingerprints them, so a hash == immutable bytes).

export interface ServiceWorkerOptions {
  /** Build-unique cache version. Changing it makes `activate` purge older caches. */
  readonly version: string;
  /** Origin-relative URLs to precache on install (the app shell). */
  readonly precache: readonly string[];
}

/** Render the service worker source (a self-contained JS string) for one build. */
export function renderServiceWorker(opts: ServiceWorkerOptions): string {
  const cacheName = `diagram-evolver-${opts.version}`;
  const precacheJson = JSON.stringify([...opts.precache]);
  return `// AUTO-GENERATED by the PWA build plugin (vite.config.ts). Do not edit by hand.
// Hand-rolled offline app-shell service worker. See src/pwa/serviceWorkerTemplate.ts.
const CACHE = ${JSON.stringify(cacheName)};
const PRECACHE = ${precacheJson};

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE)
      .then((cache) => cache.addAll(PRECACHE))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return; // never intercept cross-origin

  if (req.mode === 'navigate') {
    // Network-first: fresh HTML online; cached shell offline.
    event.respondWith(
      fetch(req)
        .then((res) => {
          const copy = res.clone();
          caches.open(CACHE).then((cache) => cache.put(req, copy));
          return res;
        })
        .catch(async () =>
          (await caches.match(req)) ||
          (await caches.match('/index.html')) ||
          (await caches.match('/')) ||
          Response.error()
        )
    );
    return;
  }

  // Static assets: cache-first (fingerprinted, hence immutable), populate on miss.
  event.respondWith(
    caches.match(req).then((hit) => {
      if (hit) return hit;
      return fetch(req).then((res) => {
        if (res && res.status === 200 && res.type === 'basic') {
          const copy = res.clone();
          caches.open(CACHE).then((cache) => cache.put(req, copy));
        }
        return res;
      });
    })
  );
});
`;
}
